import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const source = resolve(repoRoot, "target/idl/open_agora.json");
const dest = resolve(repoRoot, "apps/web/src/idl/open_agora.json");

if (!existsSync(source)) {
  if (existsSync(dest)) {
    console.log("IDL source not found (no Anchor build), using existing IDL in apps/web.");
    process.exit(0);
  }
  console.error("Missing Anchor IDL at target/idl/open_agora.json");
  console.error("Run: anchor build");
  process.exit(1);
}

// Read the new-format IDL (spec 0.1.0) generated by Anchor 0.31+
const idl = JSON.parse(readFileSync(source, "utf-8"));

// Convert to old format that @coral-xyz/anchor JS client expects
// The old format uses "programId" instead of "address" at root,
// and needs camelCase instruction/account names with "size" on accounts.
function snakeToCamel(s) {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function convertType(t) {
  if (!t) return t;
  if (typeof t === "string") return t;
  if (t.defined) return { defined: t.defined.name || t.defined };
  if (t.option) return { option: convertType(t.option) };
  if (t.vec) return { vec: convertType(t.vec) };
  if (t.array) return { array: [convertType(t.array[0]), t.array[1]] };
  return t;
}

function convertFields(fields) {
  if (!fields) return [];
  return fields.map((f) => ({
    name: snakeToCamel(f.name),
    type: convertType(f.type),
    ...(f.docs ? { docs: f.docs } : {}),
  }));
}

// Build old-format IDL
const oldIdl = {
  version: idl.metadata?.version || "0.1.0",
  name: snakeToCamel(idl.metadata?.name || "open_agora"),
  address: idl.address,
  instructions: (idl.instructions || []).map((ix) => ({
    name: snakeToCamel(ix.name),
    accounts: (ix.accounts || []).map((a) => ({
      name: snakeToCamel(a.name),
      isMut: !!a.writable,
      isSigner: !!a.signer,
      ...(a.pda ? { pda: a.pda } : {}),
      ...(a.address ? { address: a.address } : {}),
    })),
    args: (ix.args || []).map((a) => ({
      name: snakeToCamel(a.name),
      type: convertType(a.type),
    })),
    ...(ix.discriminator ? { discriminator: ix.discriminator } : {}),
  })),
  accounts: (idl.accounts || []).map((a) => ({
    name: a.name,
    discriminator: a.discriminator,
    type: {
      kind: "struct",
      fields: convertFields(
        (idl.types || []).find((t) => t.name === a.name)?.type?.fields || []
      ),
    },
  })),
  types: (idl.types || [])
    .filter((t) => t.type?.kind === "enum")
    .map((t) => ({
      name: t.name,
      type: {
        kind: "enum",
        variants: (t.type.variants || []).map((v) => ({
          name: v.name,
          ...(v.fields ? { fields: convertFields(v.fields) } : {}),
        })),
      },
    })),
  errors: (idl.errors || []).map((e) => ({
    code: e.code,
    name: e.name,
    msg: e.msg,
  })),
  metadata: {
    address: idl.address,
  },
};

mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, JSON.stringify(oldIdl, null, 2));
console.log("Synced & converted Anchor IDL -> apps/web/src/idl/open_agora.json");
